GET http://localhost:5000/api/chats/63e39354414bb17f94d3cf97 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2UyNzA5NmZkNjJjMWNlZWNiZjA4NTgiLCJlbWFpbCI6Im1haWxAbWFpbC52byIsImlhdCI6MTY3NjI5Nzg4NSwiZXhwIjoxNjc2MzAxNDg1fQ.DccOM5TLzJNb7a-SLcBo89p0hHvQ54QfjxgfwDdDGcA